name: NPM Publish

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master, test]

jobs:
  test:
    name: Pubish
    runs-on: ubuntu-latest,

    steps:
      - name: ⏬ checkout
        uses: actions/checkout@v2.1.1
      - name: 📦 Node
        uses: actions/setup-node@v1.4.2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org
    #   - name: 🚀 Publish
    #     run: npm publish --access publish
    #     env:
    #       NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
    # This is a basic workflow to help you get started with Actions
